# Generated by Django 3.0.6 on 2020-12-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='default',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('owe_name', models.CharField(max_length=64)),
                ('owe_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('owed_by_name', models.CharField(max_length=64)),
                ('owed_byamount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
        ),
    ]
