# Generated by Django 3.0.6 on 2020-12-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_auto_20201229_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khatarecord',
            options={'managed': False},
        ),
    ]
