# Generated by Django 3.0.6 on 2020-12-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_auto_20201229_1658'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='khatarecord',
            table='khatarecord',
        ),
    ]
