# Generated by Django 3.0.6 on 2020-12-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_auto_20201229_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khatarecord',
            options={'managed': True},
        ),
    ]
