# Generated by Django 3.0.6 on 2020-12-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_auto_20201229_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khatarecord',
            options={},
        ),
        migrations.AlterModelTable(
            name='khatarecord',
            table=None,
        ),
    ]
