# Generated by Django 3.0.6 on 2020-12-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_auto_20201229_1839'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='khatarecord',
            new_name='default',
        ),
    ]
